#pragma once

extern const char* literalLCID;
extern const char* literalLanguageName;
extern const char* literalLanguageNameAmerican;
extern const char* literalAlienMainMenuLabel;
extern const char* literalAlienLoadMenuLabel;
extern const char* literalAlienSettingsMenuLabel;
extern const char* literalliteralAlienAboutMenuLabel;
extern const char* literalliteralAlienHelpMenuLabel;
extern const char* literalAlienScreenSettingsMenuLabel;
extern const char* literalAlienMultiMonitorMenuLabel;
extern const char* literalAlienInGameMenuLabel;
extern const char* literalAlienLangSettingsMenuLabel;
extern const char* literalAlienContinueEmptyLabel;
extern const char* literalManufacturer;
extern const char* literalMenuContinue;
extern const char* literalMenuLoad;
extern const char* literalMenuSingle;
extern const char* literalMenuLocalMulti;
extern const char* literalMenuNetMulti;
extern const char* literalMenuSettings;
extern const char* literalMenuSave;
extern const char* literalMenuExit;
extern const char* literalMenuBack;
extern const char* literalMenuDismiss;
extern const char* literalMenuCancel;
extern const char* literalMenuOk;
extern const char* literalMenuLeave;
extern const char* literalMenuControls;
extern const char* literalMenuKnowledgebase;
extern const char* literalMenuMap;
extern const char* literalMenuInventory;
extern const char* literalSettingsMenuScreensize;
extern const char* literalSettingsMenuLanguage;
extern const char* literalSettingsMenuHelp;
extern const char* literalSettingsMenuAbout;
extern const char* literalSettingsMenuScreensizeHint;
extern const char* literalContinueEmptyHint;
extern const char* literalLoadEmptyHint;
extern const char* literalSettingsScreenTemple;
extern const char* literalSettingsScreenTempleResolution;
extern const char* literalSettingsScreenTempleDetails;
extern const char* literalSettingsScreenHercules;
extern const char* literalSettingsScreenHerculesResolution;
extern const char* literalSettingsScreenHerculesDetails;
extern const char* literalSettingsScreenModeX;
extern const char* literalSettingsScreenModeXResolution;
extern const char* literalSettingsScreenModexDetails;
extern const char* literalSettingsScreenSVGA;
extern const char* literalSettingsScreenSVGAResolution;
extern const char* literalSettingsScreenSVGADetails;
extern const char* literalSettingsScreenNotebook;
extern const char* literalSettingsScreenNotebookResolution;
extern const char* literalSettingsScreenNotebookDetails;
extern const char* literalSettingsScreenSquare;
extern const char* literalSettingsScreenSquareResolution;
extern const char* literalSettingsScreenSquareDetails;
extern const char* literalSettingsScreenFull;
extern const char* literalSettingsScreenFullResolution;
extern const char* literalSettingsScreenFullDetails;
extern const char* literalMultiMonitorMenuDisplayLabel;
extern const char* literalMessageInsufficientScreenSize;
extern const char* literalSettingsLanguageEN;
extern const char* literalSettingsLanguageENDetails;
extern const char* literalSettingsLanguageENName;
extern const char* literalSettingsLanguageFI;
extern const char* literalSettingsLanguageFIDetails;
extern const char* literalSettingsLanguageFIName;
extern const char* literalSettingsLanguageDE;
extern const char* literalSettingsLanguageDEDetails;
extern const char* literalSettingsLanguageDEName;
extern const char* literalSettingsLanguageUA;
extern const char* literalSettingsLanguageUADetails;
extern const char* literalSettingsLanguageUAName;
extern const char* literalAboutClassificationProduction;
extern const char* literalAboutClassificationProducer;
extern const char* literalAboutClassificationProducerJunior;
extern const char* literalAboutClassificationSupervisor;
extern const char* literalAboutClassificationDesign;
extern const char* literalAboutClassificationDesignOriginal;
extern const char* literalAboutClassificationDesignAdditionalMiniboss;
extern const char* literalAboutClassificationDesignQuest;
extern const char* literalAboutClassificationProgramming;
extern const char* literalAboutClassificationProgrammingEngineering;
extern const char* literalAboutClassificationProgrammingAdditional;
extern const char* literalAboutClassificationProgrammingRendering;
extern const char* literalAboutClassificationProgrammingPhysics;
extern const char* literalAboutClassificationWriters;
extern const char* literalAboutClassificationWritersStory;
extern const char* literalAboutClassificationWritersWorldbuilding;
extern const char* literalAboutClassificationWritersDialogue;
extern const char* literalAboutClassificationArtGraphics;
extern const char* literalAboutClassificationArtGraphicsCharacterDesign;
extern const char* literalAboutClassificationArtGraphicsConceptArt;
extern const char* literalAboutClassificationArtGraphicsIllustration;
extern const char* literalAboutClassificationArtGraphicsStoryboard;
extern const char* literalAboutClassificationArtGraphicsMenuHud;
extern const char* literalAboutClassificationAudio;
extern const char* literalAboutClassificationAudioComposer;
extern const char* literalAboutClassificationAudioSfx;
extern const char* literalAboutClassificationQualityAssurance;
extern const char* literalAboutClassificationQualityAssuranceTesters;
extern const char* literalAboutClassificationQualityAssurancePlaytesting;
extern const char* literalAboutClassificationQualityAssuranceCompatibility;
extern const char* literalAboutClassificationLocalization;
extern const char* literalAboutClassificationLocalizationDe;
extern const char* literalAboutClassificationLocalizationAm;
extern const char* literalAboutClassificationLocalizationFi;
extern const char* literalAboutClassificationLocalizationUa;
extern const char* literalAboutClassificationLocalizationSnailian;
extern const char* literalAboutClassificationLocalizationTranslation;
extern const char* literalAboutClassificationCreativeServices;
extern const char* literalAboutClassificationCreativeServicesCoverArt;
extern const char* literalAboutClassificationThanks;
extern const char* literalAboutClassificationThanksDedicatedTo;
extern const char* literalAboutClassificationThanksInMemoryOf;
extern const char* literalAboutClassificationThanksSpecial;
extern const char* literalAboutClassificationOther;
extern const char* literalAboutClassificationOtherTech;
extern const char* literalAboutClassificationOtherTechSDL;
extern const char* literalAboutClassificationOtherTechSDLCopyr;
extern const char* literalAboutClassificationOtherTechBox2D;
extern const char* literalAboutClassificationOtherTechBox2DCopyr;
extern const char* literalAboutClassificationOtherTechClearSans;
extern const char* literalAboutClassificationOtherTechFreckle;
extern const char* literalAboutClassificationOtherTechFreckleCopyr;
extern const char* literalAboutClassificationOtherTechYeseva;
extern const char* literalAboutClassificationOtherTechYesevaCopyr;
extern const char* literalAboutClassificationOtherTechShavian;
extern const char* literalAboutClassificationOtherTechShavianCopyr;
extern const char* literalSavegame;
extern const char* literalSavegameBlank;
extern const char* literalSavepointSingular;
extern const char* literalSavepointPlural;
extern const char* literalCreated;
extern const char* literalDialogTitleGpuChan;
extern const char* literalDialogBubbleGpuChan;
extern const char* literalregionNameUnknown;
extern const char* literalregionNameScullery;
extern const char* literalregionNameCity;
extern const char* literalregionNameLabyrinthOfUnreasonableSizeAndComplexity;
extern const char* literalregionNameDesertOfCollossalTemperatureDifferences;
extern const char* literalregionNameOceanOfImmeasurableDisappointmentAnyARuinedDay;
extern const char* literalregionNameNonMountainsOfTwoDimensionalFlatness;
extern const char* literalregionNameMarshesOfDoubtfulDrowningHazard;
extern const char* literallandmarkNameUniversityOfScience;
extern const char* literallandmarkNameLibraryOfTheUniversityOfScience;
extern const char* literallandmarkNameGardenOfRidiculouslyPoisonousPlants;
extern const char* literallandmarkNameSnurch;
extern const char* literallandmarkNameSnathedral;
extern const char* literallandmarkNameBlimpcombe;
extern const char* literallandmarkNameSoftlossnonminster;
extern const char* literalregionSensorLabel;
extern const char* literalmainQuestTitleAwning;
extern const char* literalmainQuestTitleDrawing;
extern const char* literalmainQuestTitleDrowning;
extern const char* literalmainQuestTitleKermit;
extern const char* literalmainQuestWarning;
extern const char* literalsideQuestServeAYouthfulPorpoise;
extern const char* literaldingNameWallClassic;
extern const char* literaldingNameBarrelIndigo;
extern const char* literaldingNameBarrelWood;
extern const char* literaldingNameBarrelLoaded;
extern const char* literaldingNameFloorSlate;
extern const char* literaldingNameFloorPurple;
extern const char* literaldingNameFloorOchre;
extern const char* literaldingNameFloorRock;
extern const char* literaldingNameFloorRockCracked;
extern const char* literaldingNameLettuce;
extern const char* literaldingNameSchaed;
extern const char* literaldingNameSnow;
extern const char* literaldingNameChelF;
extern const char* literaldingNameGrass;
extern const char* literaldingNameRooofMesh;
extern const char* literaldingNameHoe;
extern const char* literaldingNameHoePlural;
extern const char* literalplayerName1;
extern const char* literalplayerName2;
extern const char* literalplayerName3;
extern const char* literalplayerName4;
extern const char* literaldialogPlayer3Perennial;

namespace blooDot::en
{
	void Set();
}

namespace blooDot::de
{
	void Set();
}

namespace blooDot::fi
{
	void Set();
}

namespace blooDot::ua
{
	void Set();
}
