name: UWP 64 Release
on:
  push:
  workflow_dispatch:
jobs:
  rolling_build:
    name: UWP 64 Rolling Maintenance Build
    runs-on: windows-2019
    steps:
      - name: Install File Compression Library
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2
      
      - name: Build Solution
        shell: cmd
        run: call .\Build.cmd
        
      - name: Publish Artifact
        shell: cmd
        run: call .\ArtifactBuild.cmd
