name: UWP 64 Release
on:
  push:
  workflow_dispatch:
jobs:
  create_release:
    name: Create UWP 64 Release
    runs-on: windows-2019
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose
      - uses: actions/checkout@v2
      
      - name: Build Binary
        shell: cmd
        run: call .\Build.cmd
      - name: Build Artifact
        shell: cmd
        run: call .\ArtifactBuild.cmd
